# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IM.Control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IM.Control.proto',
  package='IM.Control',
  serialized_pb=_b('\n\x10IM.Control.proto\x12\nIM.Control\"X\n\x0eIMUserCheckReq\x12\x0f\n\x07user_id\x18\x01 \x02(\r\x12\x12\n\nsession_id\x18\x02 \x02(\r\x12\x0c\n\x04type\x18\x03 \x01(\r\x12\x13\n\x0b\x61ttach_data\x18\x14 \x01(\x0c\"_\n\x0eIMUserCheckRsp\x12\x0f\n\x07user_id\x18\x01 \x02(\r\x12\x13\n\x0bresult_code\x18\x02 \x02(\r\x12\x12\n\nresult_msg\x18\x03 \x01(\x0c\x12\x13\n\x0b\x61ttach_data\x18\x14 \x01(\x0c\x42\x1b\n\x17\x63om.mogujie.tt.protobufH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMUSERCHECKREQ = _descriptor.Descriptor(
  name='IMUserCheckReq',
  full_name='IM.Control.IMUserCheckReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='IM.Control.IMUserCheckReq.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='IM.Control.IMUserCheckReq.session_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='IM.Control.IMUserCheckReq.type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attach_data', full_name='IM.Control.IMUserCheckReq.attach_data', index=3,
      number=20, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=120,
)


_IMUSERCHECKRSP = _descriptor.Descriptor(
  name='IMUserCheckRsp',
  full_name='IM.Control.IMUserCheckRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='IM.Control.IMUserCheckRsp.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result_code', full_name='IM.Control.IMUserCheckRsp.result_code', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result_msg', full_name='IM.Control.IMUserCheckRsp.result_msg', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attach_data', full_name='IM.Control.IMUserCheckRsp.attach_data', index=3,
      number=20, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=217,
)

DESCRIPTOR.message_types_by_name['IMUserCheckReq'] = _IMUSERCHECKREQ
DESCRIPTOR.message_types_by_name['IMUserCheckRsp'] = _IMUSERCHECKRSP

IMUserCheckReq = _reflection.GeneratedProtocolMessageType('IMUserCheckReq', (_message.Message,), dict(
  DESCRIPTOR = _IMUSERCHECKREQ,
  __module__ = 'IM.Control_pb2'
  # @@protoc_insertion_point(class_scope:IM.Control.IMUserCheckReq)
  ))
_sym_db.RegisterMessage(IMUserCheckReq)

IMUserCheckRsp = _reflection.GeneratedProtocolMessageType('IMUserCheckRsp', (_message.Message,), dict(
  DESCRIPTOR = _IMUSERCHECKRSP,
  __module__ = 'IM.Control_pb2'
  # @@protoc_insertion_point(class_scope:IM.Control.IMUserCheckRsp)
  ))
_sym_db.RegisterMessage(IMUserCheckRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027com.mogujie.tt.protobufH\003'))
# @@protoc_insertion_point(module_scope)
